services:
  db:
    image: postgres:latest
    container_name: project-management-db
    environment:
      POSTGRES_DB: project_management_db
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: project-management-app
    ports:
      - "8080:8080"
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: admin
      DB_PASSWORD: password
      DB_NAME: project_management_db
    depends_on:
      - db

volumes:
  pgdata: